metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  co2-emissions:
    envs:
    - host
    path: pipelines/co2-emissions
    stages:
    - setup
    - run
    - validate
  experiment1:
    envs:
    - host
    path: pipelines/experiment1
    stages:
    - setup
    - run
    - post-run
    - validate
    - teardown
popperized:
- github/popperized
